version: "3.8"
services:
  react-app:
    container_name: react
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "${CLIENTPORT}:${CLIENTPORT}"
    volumes:
      - ./react:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - app-network

  express-app:
    container_name: express-app
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${SERVERPORT}:${SERVERPORT}"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - ORIGIN=${ORIGIN}
      - SERVERPORT=${SERVERPORT}
      - MONGO_DB=${MONGO_DB}
      - DB_NAME=${DB_NAME}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
