version: "3.8"
services:
  react-app:
    container_name: react
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network

  express-app:
    container_name: express-app
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
