version: "3.8"
services:
  react-app:
    container_name: react
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "${CLIENTPORT}:${CLIENTPORT}"
    volumes:
      - ./react:/app
      - /app/node_modules
    networks:
      - app-network

  express-app:
    container_name: express-app
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${SERVERPORT}:${SERVERPORT}"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - HOST=${HOST}
      - SERVERPORT=${SERVERPORT}
      - CLIENTPORT=${CLIENTPORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
